Add auto-refresh to JWT
codeforboston/police-data-trust pull request #158
Opened 2021-09-21 23:51 UTC by ryanmahan

Added: 
+ header and cookie support. Check the header first, if not present check the cookie
+ auto-refresh cookies on every API call, via a post-request function
+ refresh token endpoint that returns a new valid token for API users
  - Not sure if this is implemented correctly, I use the auth token and not the refresh token to validate this
- test for /auth/test endpoint and cookie setting
- Config vars for setting cookies securely and preventing forgery in production

Removed:
None

Aligns with issue #2 and somewhat to #104, we only store basic information and role as an enum currently.

2021-09-27 13:57 UTC, JMStudiosJoe approved these changes

2021-09-27 16:01 UTC, alexjball requested changes
Minor config changes requested, but LGTM once addressed!

2021-10-01 19:10 UTC, ryanmahan commented on backend/auth/auth.py
> +        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
what's the best way to import config variables into this file? I see api.py calls `get_config_from_env(config or app.env)` but I have no access to the api.py local var `config` here.

2021-10-04 15:32 UTC, alexjball commented on backend/auth/auth.py
> +        target_timestamp = datetime.timestamp(now + timedelta(minutes=30))
Hey @ryanmahan you can `from flask import current_app` and reference the config as `current_app.config`. current_app is set to the flask app that is handing the current request. See an example [here](https://github.com/codeforboston/police-data-trust/blob/08a1b4d7f81b8cb64742df620f06358ce3a6219c/backend/database/core.py#L112)

2021-10-14 01:55 UTC, merged