officer end point
codeforboston/police-data-trust pull request #326
Opened 2024-02-15 18:02 UTC by zeelapatel

Created an officer search end point by replicating incident search end point 
out put can be changed as which data we want to display in json format

2024-02-16 20:14 UTC, DMalone87 requested changes
Looking good! Just need to make a few adjustments.

2024-02-16 20:14 UTC, DMalone87 commented on backend/routes/incidents.py
Let's move these endpoints into a separate file, `officers.py`. It helps to keep things organized. We'll need to add tests as well.

2024-02-16 20:14 UTC, DMalone87 commented on backend/schemas.py
Looks good!

2024-02-17 00:03 UTC, zeelapatel commented on backend/routes/incidents.py
okay I will create a separate file for it.
if there is any other changes please let me know. thank you

2024-02-27 20:03 UTC, DMalone87 commented on backend/routes/incidents.py
We can drop all changes from this file as well since it shouldn't be affected by the Officer endpoints.

2024-02-27 20:03 UTC, DMalone87 commented on frontend/compositions/search-panel/search-panel.tsx
> +
Let's drop this change as well.

2024-02-28 19:02 UTC, DMalone87 commented
Thanks, Zeel! There are some style issues, but for this one, I'll go ahead and merge and make the corrections.

2024-02-28 19:02 UTC, merged